apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: visitantes
  description: API Go Visit - Endpoints visitantes 
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/CzR21/backstage_plugin/blob/main/api/openapi-visitante.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: local
  description: API Go Visit - Endpoints local
spec:
  type: openapi
  lifecycle: production
  owner: team-b
  definition:
    $text: https://github.com/CzR21/backstage_plugin/blob/main/api/openapi-local.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: aprovador
  description: API Go Visit - Endpoints aprovador
spec:
  type: openapi
  lifecycle: production
  owner: team-c
  definition:
    $text: https://github.com/CzR21/backstage_plugin/blob/main/api/openapi-aprovador.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: convite
  description: API Go Visit - Endpoints convite
spec:
  type: openapi
  lifecycle: production
  owner: team-d
  definition:
    $text: https://github.com/CzR21/backstage_plugin/blob/main/api/openapi-convite.yaml